wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    is_jupyter_run: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 117
buckets:
  desc: null
  value: 31
epochs:
  desc: null
  value: 91
max_len:
  desc: null
  value: 7
