wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    is_jupyter_run: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 91
buckets:
  desc: null
  value: 10
epochs:
  desc: null
  value: 64
max_len:
  desc: null
  value: 6
